-- MySQL Script generated by MySQL Workbench
-- Thu 10 Dec 2015 07:33:14 PM AST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema api_maturity
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `api_maturity` ;

-- -----------------------------------------------------
-- Schema api_maturity
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `api_maturity` DEFAULT CHARACTER SET utf8 ;
USE `api_maturity` ;

-- -----------------------------------------------------
-- Table `api_maturity`.`Form`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `api_maturity`.`Form` ;

CREATE TABLE IF NOT EXISTS `api_maturity`.`Form` (
  `id` INT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `api_maturity`.`Client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `api_maturity`.`Client` ;

CREATE TABLE IF NOT EXISTS `api_maturity`.`Client` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `api_maturity`.`Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `api_maturity`.`Category` ;

CREATE TABLE IF NOT EXISTS `api_maturity`.`Category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `api_maturity`.`Group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `api_maturity`.`Group` ;

CREATE TABLE IF NOT EXISTS `api_maturity`.`Group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `api_maturity`.`Question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `api_maturity`.`Question` ;

CREATE TABLE IF NOT EXISTS `api_maturity`.`Question` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(200) NULL,
  `category_id` INT NOT NULL,
  `form_id` INT NOT NULL,
  `group_id` INT NULL,
  PRIMARY KEY (`id`, `category_id`),
  INDEX `fk_Question_Category_idx` (`category_id` ASC),
  INDEX `fk_Question_Form1_idx` (`form_id` ASC),
  INDEX `fk_Question_Grouping1_idx` (`group_id` ASC),
  CONSTRAINT `fk_Question_Category`
    FOREIGN KEY (`category_id`)
    REFERENCES `api_maturity`.`Category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Question_Form1`
    FOREIGN KEY (`form_id`)
    REFERENCES `api_maturity`.`Form` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Question_Grouping1`
    FOREIGN KEY (`group_id`)
    REFERENCES `api_maturity`.`Group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `api_maturity`.`Response`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `api_maturity`.`Response` ;

CREATE TABLE IF NOT EXISTS `api_maturity`.`Response` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `response` VARCHAR(45) NULL,
  `value` INT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Response_Category1_idx` (`category_id` ASC),
  CONSTRAINT `fk_Response_Category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `api_maturity`.`Category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `api_maturity`.`ClientQuestionResponse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `api_maturity`.`ClientQuestionResponse` ;

CREATE TABLE IF NOT EXISTS `api_maturity`.`ClientQuestionResponse` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `response_id` INT NOT NULL DEFAULT 1,
  `question_id` INT NOT NULL,
  `client_id` INT NOT NULL,
  `weight` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_ClientQuestionResponse_Response1_idx` (`response_id` ASC),
  INDEX `fk_ClientQuestionResponse_Question1_idx` (`question_id` ASC),
  INDEX `fk_ClientQuestionResponse_Client1_idx` (`client_id` ASC),
  CONSTRAINT `fk_ClientQuestionResponse_Response1`
    FOREIGN KEY (`response_id`)
    REFERENCES `api_maturity`.`Response` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ClientQuestionResponse_Question1`
    FOREIGN KEY (`question_id`)
    REFERENCES `api_maturity`.`Question` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ClientQuestionResponse_Client1`
    FOREIGN KEY (`client_id`)
    REFERENCES `api_maturity`.`Client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
